---
title: "Clustering and viewing compareClusterResult"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Clustering and viewing compareClusterResult}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(EnrichGT)
```

# Object containing multiple enrichment results

EnrichGT supports `compareClusterResult` or a `data.frame` with column "Cluster" containing group informations. 

```{r}
suppressMessages({
  library(tidyverse)
  library(gt)
  library(clusterProfiler)
  library(org.Hs.eg.db)
  })
data(gcSample)
ck <- compareCluster(geneCluster = gcSample, fun = enrichGO, OrgDb = org.Hs.eg.db, pvalueCutoff = 0.5, qvalueCutoff = 0.5,ont="BP")
ck <- setReadable(ck, OrgDb = org.Hs.eg.db, keyType = "ENTREZID")
sd <- EnrichGT(ck, ClusterNum = 3, P.adj = 1)
str(sd,max.level=3)
```

Return a `list` containing `EnrichGT_obj` of each `compareClusterResult`. 

# Session info

```{r}
sessioninfo::session_info()
```
