---
title: "Get Start"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get Start}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(EnrichGT)
```


# Get Start

## Enrich the enriched result (enrich^2)

First enrich genes by `clusterProfiler`...

```{r include=FALSE}
suppressMessages({
  library(tidyverse)
  library(gt)
  library(clusterProfiler)
  library(org.Hs.eg.db)
  })
data(geneList, package="DOSE")
gene <- names(geneList)[abs(geneList) > 2]
```


```{r}
ego <- enrichGO(gene          = gene,
                  universe      = names(geneList),
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.5,
                  qvalueCutoff  = 0.5,
                  readable      = TRUE)
```

Then, run  `obj |> EnrichGT()` !

```{r}
obj <- ego |> EnrichGT()
```

```{r}
obj@gt_object
```


For further guidance, see other `Articles`.  

# Visualize

## Dot Plot

```{r fig.height=9, fig.width=7}
egtPlot(obj)
```

## UMAP visualization

```{r fig.height=7, fig.width=7}
egtScatter(obj)
```

# Session info

```{r}
sessioninfo::session_info()
```

