library(dplyr)
library(tibble)
library(ggplot2)
if(!require(org.Hs.eg.db)){
  pak::pkg_install("org.Hs.eg.db")
}
library(org.Hs.eg.db)
library(gt)
library(EnrichGT)
library(readr)
library(testthat)
# Generated by deepseek AI (r1). 
test_that("Data filtering and basic analysis works", {
  # 加载测试数据
  data("DEGexample", package = "EnrichGT")
  
  # 测试基本过滤
  DEGexample2 <- DEGexample |> dplyr::filter(pvalue < 0.05)
  expect_gt(nrow(DEGexample2), 0)
  
  DEGexample_UpReg <- DEGexample |> dplyr::filter(pvalue < 0.05, log2FoldChange > 0.7)
  expect_gt(nrow(DEGexample_UpReg), 0)
})

test_that("Enrichment analysis functions work", {
  data("DEGexample", package = "EnrichGT")
  
  # 准备测试数据
  DEGexample_UpReg <- DEGexample |> dplyr::filter(pvalue < 0.05, log2FoldChange > 0.7)
  DEGs <- DEGexample_UpReg$...1
  
  # ORA分析测试
  ora_result <- egt_enrichment_analysis(
    genes = DEGs, 
    database = database_GO_BP(OrgDB = org.Hs.eg.db)
  )
  expect_gt(nrow(ora_result), 2)
  
  # KEGG数据库测试
  keggRes <- database_KEGG()
  expect_gt(nrow(keggRes), 2)
})

test_that("Recluster analysis works", {
  data("DEGexample", package = "EnrichGT")
  
  DEGexample_UpReg <- DEGexample |> dplyr::filter(pvalue < 0.05, log2FoldChange > 0.7)
  DEGs <- DEGexample_UpReg$...1
  
  ora_result <- egt_enrichment_analysis(
    genes = DEGs, 
    database = database_GO_BP(OrgDB = org.Hs.eg.db)
  )
  
  # 重聚类测试
  re_enrichment_results <- egt_recluster_analysis(ora_result)
  expect_s4_class(re_enrichment_results, "EnrichGT_obj")
  expect_true("gt_tbl" %in% class(re_enrichment_results@gt_object))
})

test_that("Visualization functions work", {
  data("DEGexample", package = "EnrichGT")
  
  DEGexample_UpReg <- DEGexample |> dplyr::filter(pvalue < 0.05, log2FoldChange > 0.7)
  DEGs <- DEGexample_UpReg$...1
  
  ora_result <- egt_enrichment_analysis(
    genes = DEGs, 
    database = database_GO_BP(OrgDB = org.Hs.eg.db)
  )
  
  # 绘图功能测试
  plt1 <- egt_plot_results(ora_result, showIDs = TRUE, ntop = 20)
  expect_s3_class(plt1, "gg")
  
  re_enrichment_results <- egt_recluster_analysis(ora_result)
  plt2 <- egt_plot_results(re_enrichment_results)
  expect_s3_class(plt2, "gg")
})

test_that("GSEA analysis works", {
  data("DEGexample", package = "EnrichGT")
  
  DEGexample2 <- DEGexample |> dplyr::filter(pvalue < 0.05)
  genes_with_weights <- genes_with_weights(DEGexample2$...1, DEGexample2$log2FoldChange)
  
  # GSEA分析测试
  GSEAexample <- egt_gsea_analysis(
    genes = genes_with_weights,
    database = database_Reactome(OrgDB = org.Hs.eg.db)
  )
  expect_gt(nrow(GSEAexample), 2)
  
  # GSEA绘图测试
  ll <- egt_plot_gsea(
    GSEAexample$Description[99],
    genes = genes_with_weights,
    database = database_Reactome(OrgDB = org.Hs.eg.db)
  )
  expect_s3_class(ll, "gg")
  
  ll2 <- egt_plot_gsea(
    GSEAexample[1:3, ],
    genes = genes_with_weights,
    database = database_Reactome(OrgDB = org.Hs.eg.db)
  )
  expect_s3_class(ll2, "gg")
  
  # GSEA重聚类测试
  re_enrichment_results_gsea <- egt_recluster_analysis(GSEAexample)
  expect_s4_class(re_enrichment_results_gsea, "EnrichGT_obj")
})