#' @title Return ranked gene list which is use for "GSEA" and "cnetplot" in package "clusterProfiler"
#'
#' @param Gene A vector containing genes
#' @param log2FC A vector containg log2FC
#' @param FromType default is "SYMBOL"
#' @param OrgDB default as org.Hs.eg.db
#'
#' @return A ranked named numeric vector. Names of the numbers is the ENTREZID.
#' @export
#' @author Zhiming Ye
#'
Ranked.GS<-function(Gene,log2FC,FromType = "SYMBOL",OrgDB=org.Hs.eg.db){
  Genetable<-data.frame(Gene=Gene,log2FC=log2FC)
  require(clusterProfiler)
  ENTREZIDtable<-clusterProfiler::bitr(Genetable$Gene,fromType = FromType,toType = "ENTREZID",OrgDb = OrgDB)
  colnames(ENTREZIDtable)[1]<-"Gene"
  Genetable<-Genetable%>%left_join(ENTREZIDtable)%>%arrange(desc(log2FC))
  GSElist<-as.numeric(Genetable$log2FC)
  names(GSElist)<-Genetable$ENTREZID
  GSElist = sort(GSElist, decreasing = TRUE)
  return(GSElist)
}
#' @title ORA GO analysis by clusterProfiler by symbol identifiers.
#'
#' @param GS Gene Symbols for enrichment analysis. NOT ENSEMBL ID.
#' @param ont One of "BP", "CC", "MF"  and "ALL".
#' @param PVal P adjusted value cut off, default 0.01
#' @param QVal qvalue cut off, default 0.05
#' @param OrgDB default as org.Hs.eg.db
#'
#' @return An enrichment result generated by clusterProfiler.
#' @export
#' @author Zhiming Ye
#'
doGO<-function(GS,ont="BP",PVal=0.01,QVal=0.05,OrgDB=org.Hs.eg.db){
  require(clusterProfiler)
  GeneList<-GS%>%unique()%>%clusterProfiler::bitr(fromType = "SYMBOL",toType = "ENTREZID",OrgDb = OrgDB)
  EnrichGO<-clusterProfiler::enrichGO(GeneList$ENTREZID,ont = ont,OrgDb = OrgDB,pvalueCutoff = PVal,qvalueCutoff = QVal)%>%clusterProfiler::setReadable(OrgDb=OrgDB,keyType = "ENTREZID")
  return(EnrichGO)
}
#' @title ORA KEGG analysis by clusterProfiler by symbol identifiers.
#'
#' @param GS Gene Symbols for enrichment analysis. NOT ENSEMBL ID.
#' @param PVal P adjusted value cut off, default 0.01
#' @param QVal qvalue cut off, default 0.05
#' @param Organism supported organism listed in 'https://www.genome.jp/kegg/catalog/org_list.html'
#' @param OrgDB default as org.Hs.eg.db
#'
#' @return An enrichment result generated by clusterProfiler.
#' @export
#' @author Zhiming Ye
#'
doKEGG<-function(GS,PVal=0.01,QVal=0.05,Organism="hsa",OrgDB=org.Hs.eg.db){
  require(clusterProfiler)
  GeneList<-GS%>%unique()%>%clusterProfiler::bitr(fromType = "SYMBOL",toType = "ENTREZID",OrgDb = OrgDB)
  EnrichKEGG<-clusterProfiler::enrichKEGG(GeneList$ENTREZID,pvalueCutoff = PVal,qvalueCutoff = QVal,organism=Organism)%>%clusterProfiler::setReadable(OrgDb=OrgDB,keyType = "ENTREZID")
  return(EnrichKEGG)
}
#' @title ORA Reactome analysis by clusterProfiler by symbol identifiers.
#'
#' @param GS Gene Symbols for enrichment analysis. NOT ENSEMBL ID.
#' @param PVal P adjusted value cut off, default 0.01
#' @param QVal qvalue cut off, default 0.05
#' @param Organism one of "human", "rat", "mouse", "celegans", "yeast", "zebrafish", "fly".
#' @param OrgDB default as org.Hs.eg.db
#'
#' @return An enrichment result generated by clusterProfiler.
#' @export
#' @author Zhiming Ye
#'
doRA<-function(GS,PVal=0.01,QVal=0.05,Organism="human",OrgDB=org.Hs.eg.db){
  require(clusterProfiler)
  require(ReactomePA)
  GeneList<-GS%>%unique()%>%clusterProfiler::bitr(fromType = "SYMBOL",toType = "ENTREZID",OrgDb = OrgDB)
  EnrichRA<-ReactomePA::enrichPathway(GeneList$ENTREZID,pvalueCutoff = PVal,qvalueCutoff = QVal,organism=Organism)%>%clusterProfiler::setReadable(OrgDb=OrgDB,keyType = "ENTREZID")
  return(EnrichRA)
}
#' @title Build up a DEG data frame for clusterProfiler multi-group ORA analysis
#' @description Convert symbol, and add up group name in column.
#' @param Gene A vector containing genes.
#' @param Group A character of group name
#' @param OrgDB Default as org.Hs.eg.db
#'
#' @return A data frame. Following rbind command can help you build up the full DEG list.
#' @export
#' @author Zhiming Ye
#'
BuildMultigroupDEGlist<-function(Gene,Group,OrgDB=org.Hs.eg.db){
  require(clusterProfiler)
  Genetable <- data.frame(Gene = Gene, Group = Group)
  ENTREZIDtable <- clusterProfiler::bitr(Genetable$Gene, fromType = "SYMBOL",
                                         toType = "ENTREZID", OrgDb = OrgDB)
  colnames(ENTREZIDtable)[1] <- "Gene"
  Genetable <- Genetable %>% left_join(ENTREZIDtable)
  return(Genetable)
}

