#' @importFrom RColorBrewer brewer.pal
#' @importFrom fontawesome fa
#' @importFrom gt gt tab_style row_group_order cells_body tab_header cell_text from_column
gt_gsea <- function(x, ClusterNum, objname, objname2 = NULL, ...) {
  if (!is.null(objname2)) {
    objname <- objname2
  }
  orderlist <- fix_order(x$Cluster)
  orderlist <- orderlist[orderlist %in% x$Cluster]
  if (sum(x$ID == x$Description) >= 5) {
    x$ID <- paste0(objname, " / ", 1:nrow(x))
  }
  y <- x |>
    gt::gt(groupname_col = "Cluster") |>
    gt_hulk_col_numeric2(Padj, pal = RColorBrewer::brewer.pal(8, "Spectral")) |>
    gt_hulk_col_numeric2(
      absNES,
      pal = RColorBrewer::brewer.pal(8, "PuBuGn") |> rev()
    ) |>
    # gt::cols_add(dir = ifelse(Reg=="Up", "red", "forestgreen")) |>
    gt::cols_label(Reg = "") |>
    gt::text_case_match(
      "red" ~ fontawesome::fa("arrow-up"),
      "forestgreen" ~ fontawesome::fa("arrow-down")
    ) |>
    gt::tab_style(
      style = gt::cell_text(color = gt::from_column("Reg")),
      locations = gt::cells_body(columns = Reg)
    ) |>
    gt::tab_style(
      style = gt::cell_text(size = gt::px(13)),
      locations = gt::cells_body()
    ) |>
    gt::row_group_order(groups = c(orderlist)) |>
    gt_merge_stack2(col2 = ID, col1 = Description) |>
    gt::tab_header(
      title = paste0("Parse form: ", objname),
      subtitle = paste0(
        "Split into ",
        ClusterNum,
        " Clusters. Generated by github@zhimingye/EnrichGT"
      )
    )
  return(y)
}

gt_ora <- function(x, ClusterNum, objname, objname2 = NULL, ...) {
  if (!is.null(objname2)) {
    objname <- objname2
  }
  orderlist <- fix_order(x$Cluster)
  orderlist <- orderlist[orderlist %in% x$Cluster]
  if (sum(x$ID == x$Description) >= 5) {
    x$ID <- paste0(objname, " / ", 1:nrow(x))
  }
  y <- x |>
    gt::gt(groupname_col = "Cluster") |>
    gt_hulk_col_numeric2(
      PCT,
      pal = RColorBrewer::brewer.pal(8, "PiYG") |> rev()
    ) |>
    gt_hulk_col_numeric2(Padj, pal = RColorBrewer::brewer.pal(8, "Spectral")) |>
    gt_hulk_col_numeric2(
      Count,
      pal = RColorBrewer::brewer.pal(8, "PuBuGn") |> rev()
    ) |>
    gt::tab_style(
      style = gt::cell_text(size = gt::px(13)),
      locations = gt::cells_body()
    ) |>
    gt::row_group_order(groups = c(orderlist)) |>
    gt_merge_stack2(col2 = ID, col1 = Description) |>
    gt::tab_header(
      title = paste0("Parse form: ", objname),
      subtitle = paste0(
        "Split into ",
        ClusterNum,
        " Clusters. Generated by github@zhimingye/EnrichGT"
      )
    )
  return(y)
}

fix_order <- function(x) {
  max_num <- max(gsub("Cluster_", "", x) |> as.numeric())
  return(paste0("Cluster_", 1:max_num))
}


gt_gsea_raw <- function(x, ClusterNum, objname, objname2 = NULL, ...) {
  if (!is.null(objname2)) {
    objname <- objname2
  }
  orderlist <- fix_order(x$Cluster)
  orderlist <- orderlist[orderlist %in% x$Cluster]
  if (sum(x$ID == x$Description) >= 5) {
    x$ID <- paste0(objname, " / ", 1:nrow(x))
  }
  x <- x |> dplyr::select(-core_enrichment) #core_enrichment
  y <- x |>
    gt::gt(groupname_col = "Cluster") |>
    # gt::cols_add(dir = ifelse(Reg=="Up", "red", "forestgreen")) |>
    gt::cols_label(Reg = "") |>
    gt::text_case_match(
      "red" ~ fontawesome::fa("arrow-up"),
      "forestgreen" ~ fontawesome::fa("arrow-down")
    ) |>
    gt::tab_style(
      style = gt::cell_text(color = gt::from_column("Reg")),
      locations = gt::cells_body(columns = Reg)
    ) |>
    gt::tab_style(
      style = gt::cell_text(size = gt::px(13)),
      locations = gt::cells_body()
    ) |>
    gt::row_group_order(groups = c(orderlist)) |>
    gt::tab_header(
      title = paste0("Parse form: ", objname),
      subtitle = paste0(
        "Split into ",
        ClusterNum,
        " Clusters. Generated by github@zhimingye/EnrichGT"
      )
    ) |> gt::cols_width(
      Description ~ "120pt",
      ID ~ "40pt",
      Reg ~ "20pt",
      Padj ~ "20pt")
  return(y)
}

gt_ora_raw <- function(x, ClusterNum, objname, objname2 = NULL, ...) {
  
  if (!is.null(objname2)) {
    objname <- objname2
  }
  orderlist <- fix_order(x$Cluster)
  orderlist <- orderlist[orderlist %in% x$Cluster]
  if (sum(x$ID == x$Description) >= 5) {
    x$ID <- paste0(objname, " / ", 1:nrow(x))
  }
  x <- x |> dplyr::select(-geneID) #core_enrichment
  y <- x |>
    gt::gt(groupname_col = "Cluster") |>
    gt::tab_style(
      style = gt::cell_text(size = gt::px(13)),
      locations = gt::cells_body()
    ) |>
    gt::row_group_order(groups = c(orderlist)) |>
    gt::tab_header(
      title = paste0("Parse form: ", objname),
      subtitle = paste0(
        "Split into ",
        ClusterNum,
        " Clusters. Generated by github@zhimingye/EnrichGT"
      )
    ) |> gt::cols_width(
      Description ~ "150pt",
      ID ~ "80pt",
      Count ~ "20pt",
      PCT ~ "20pt",
      Padj ~ "20pt")
  return(y)
}
