gt_gsea<-function(x,ClusterNum,objname,...){
  y<-x |> gt::gt(groupname_col = "Cluster") |>
    gt_hulk_col_numeric2(Padj,pal = RColorBrewer::brewer.pal(8,"Spectral")) |>
    gt_hulk_col_numeric2(absNES,pal = RColorBrewer::brewer.pal(8,"PuBuGn") |> rev()) |>
    gt_merge_stack2(col2 = ID, col1 = Description) |>
    # gt::cols_add(dir = ifelse(Reg=="Up", "red", "forestgreen")) |>
    gt::cols_label(Reg = "") |>
    gt::text_case_match(
      "red" ~ fontawesome::fa("arrow-up"),
      "forestgreen" ~ fontawesome::fa("arrow-down")
    ) |>
    gt::tab_style(
      style = cell_text(color = from_column("Reg")),
      locations = cells_body(columns = Reg)
    ) |>
    gt::tab_style(
      style = cell_text(size = px(13)),
      locations = cells_body()
    ) |>
    gt::tab_header(title =paste0("Parse form: ",objname),subtitle = paste0("Split into ",ClusterNum, " Clusters. Generated by github@zhimingye/EnrichGT"))
  return(y)
}

gt_ora<-function(x,ClusterNum,objname,...){
  y<-x |> gt::gt(groupname_col = "Cluster") |>
    gt_hulk_col_numeric2(PCT,pal = RColorBrewer::brewer.pal(8,"PiYG") |> rev()) |>
    gt_hulk_col_numeric2(Padj,pal = RColorBrewer::brewer.pal(8,"Spectral")) |>
    gt_hulk_col_numeric2(Count,pal = RColorBrewer::brewer.pal(8,"PuBuGn") |> rev()) |>
    gt_merge_stack2(col2 = ID, col1 = Description) |>
    gt::tab_style(
      style = cell_text(size = px(13)),
      locations = cells_body()
    ) |>
    gt::tab_header(title =paste0("Parse form: ",objname),subtitle = paste0("Split into ",ClusterNum, " Clusters. Generated by github@zhimingye/EnrichGT"))
  return(y)
}
