
setGeneric("EnrichGT",function(x,ClusterNum,P.adj=0.05,...) standardGeneric("EnrichGT"))
setMethod("EnrichGT", signature(x = "enrichResult"),function(x,...){
  y<-.genGT(x=x@result,...)
  return(y)
})
setMethod("EnrichGT", signature(x = "compareClusterResult"),function(x,...){
  x<-split(x@result,x@result$cluster)
  y<-lapply(x, function(x).genGT(x))
  return(y)
})
setMethod("EnrichGT", signature(x = "gseaResult"),function(x,...){
  y<-.genGSEAGT(x=x@result,...)
  return(y)
})
setMethod("EnrichGT", signature(x = "data.frame"),function(x,...){
  if("NES"%in%colnames(x)){
    y<-.genGSEAGT(x=x,...)
    return(y)
  }
  else if("cluster"%in%colnames(x)){
    x<-split(x,x$cluster)
    y<-lapply(x, function(x).genGT(x))
    return(y)
  }
  else{
    y<-.genGT(x=x,...)
    return(y)
  }
})
is_numeric_string <- function(x) {
  grepl("^-?\\d+(\\.\\d+)?$", x)
}
.enrichpws<-function(ID,geneID,k,sep="/"){
  require(proxy)
  require(text2vec)
  tokens_list <- strsplit(geneID,sep)
  tokens_list<-lapply(tokens_list,function(x){
    x[is_numeric_string(x)]<-paste0("Gene_",x)
  })
  names(tokens_list)<-ID
  tokens_iter <- text2vec::itoken(tokens_list, progressbar = FALSE)
  vocab <- text2vec::create_vocabulary(tokens_iter)
  vectorizer <- text2vec::vocab_vectorizer(vocab)
  dtm <- text2vec::create_dtm(tokens_iter, vectorizer)
  distance_matrix <- proxy::dist(dtm |> as.matrix(), method = "cosine")
  hc <- hclust(distance_matrix, method = "ward.D2")
  plot(hc)
  clusters <- cutree(hc, k = k)
  clusters<-clusters |> as.data.frame() |> tibble::rownames_to_column(var="ID") |> dplyr::rename(Cluster=".")
  clusters$Cluster<-paste0("Cluster_",clusters$Cluster)
  return(clusters)
}


.genClusterNum<-function(ClusterNum,force){
  if(!force){
    ClusterNum0<-ClusterNum
    ClusterNum<-dplyr::case_when(dim(x)[1]<10~1,
                                 dim(x)[1]<20~2,
                                 dim(x)[1]<30~2,
                                 dim(x)[1]<40~3,
                                 dim(x)[1]<50~3,
                                 dim(x)[1]>=50~ClusterNum0)
    if(ClusterNum>60){
      message("Too many clusters! Try with max as 50...\nuse force=T to forbid the self-check")
      ClusterNum<-60
    }
    if(ClusterNum>dim(x)[1]/10 & dim(x)[1]>=50){
      message("Too many clusters! Try with max as ncol/10...\nuse force=T to forbid the self-check")
      ClusterNum<-dim(x)[1]/11
    }
  }
  else{
    ClusterNum<-ClusterNum0
  }
  return(ClusterNum)
}
.checkNrows<-function(x,force){
  if(nrow(x)>1000&!force){
    stop("Too many rows!(>1000), please subset! use force=T to forbid the self-check")
  }
  if(nrow(x)>750){
    message("Too many rows! It might be slow...\nWorking, but please consider increase P.adj ...")
  }
}
.checkRowNames<-function(x,TYPE){
  enrichRescolnames<-c("ID","Description","GeneRatio","BgRatio","pvalue","p.adjust","qvalue","geneID","Count")
}
.get_object_name <- function(x) {
  deparse(substitute(x))
}
.genGT<-function(x,ClusterNum,P.adj=0.05,force=F,...){
  objname<-.get_object_name(x)
  InnerDF<-x
  ClusterNum0<-ClusterNum
  ClusterNum<-.genClusterNum(ClusterNum = ClusterNum0,force = force)
  InnerDF<-InnerDF |> dplyr::left_join(.enrichpws(InnerDF$ID,InnerDF$geneID,ClusterNum)) # Merge according to "ID"
  InnerDF<-InnerDF |> dplyr::filter(pvalue<0.05,Count>=5,p.adjust<P.adj) |> dplyr::select(-c(pvalue,qvalue,BgRatio)) # Need Fix
  .checkNrows(InnerDF,force = force)
  obj<-InnerDF |>
    dplyr::mutate(PCT=sapply(InnerDF$GeneRatio,function(x)eval(parse(text = x)))*100) |>
    dplyr::mutate(Padj = signif(p.adjust, 2),PCT=signif(PCT, 2)) |>
    dplyr::select(Description,ID,Count,Cluster,PCT,Padj,geneID) |>
    dplyr::mutate(geneID=gsub("/"," ,",geneID))|>
    gt::gt(groupname_col = "Cluster") |>
    gt_hulk_col_numeric2(PCT,pal = RColorBrewer::brewer.pal(8,"PiYG") |> rev()) |>
    gt_hulk_col_numeric2(Padj,pal = RColorBrewer::brewer.pal(8,"Spectral")) |>
    gt_hulk_col_numeric2(Count,pal = RColorBrewer::brewer.pal(8,"PuBuGn") |> rev()) |>
    gt_merge_stack2(col2 = ID, col1 = Description) |>
    gt::cols_width(Count ~ px(100),
               PCT ~ px(100)) |>
    gt::tab_style(
      style = cell_text(size = px(13)),
      locations = cells_body()
    ) |>
    gt::tab_header(title =paste0("Parse form: ",objname),subtitle = paste0("Split into ",k, " Clusters. Generated by zhimingye/Enrich2GT"))
  return(obj)
}
# attachment::att_amend_desc()
