
setGeneric("EnrichGT",function(x,ClusterNum,P.adj=0.05,...) standardGeneric("EnrichGT"))
setMethod("EnrichGT", signature(x = "enrichResult"),function(x,...){
  .genGT(x=x@result,...)
})
setMethod("EnrichGT", signature(x = "compareClusterResult"),function(x,...){
  x<-split(x@result,x@result$cluster)
  .genGT(x=x,...)
})
setMethod("EnrichGT", signature(x = "gseaResult"),function(x,...){
  .genGSEAGT(x=x@result,...)
})
setMethod("EnrichGT", signature(x = "data.frame"),function(x,...){

})

.enrichpws<-function(ID,geneID,k,sep="/"){
  require(proxy)
  require(text2vec)
  tokens_list <- strsplit(geneID,sep)
  names(tokens_list)<-ID
  tokens_iter <- text2vec::itoken(tokens_list, progressbar = FALSE)
  vocab <- text2vec::create_vocabulary(tokens_iter)
  vectorizer <- text2vec::vocab_vectorizer(vocab)
  dtm <- text2vec::create_dtm(tokens_iter, vectorizer)
  distance_matrix <- proxy::dist(dtm |> as.matrix(), method = "cosine")
  hc <- hclust(distance_matrix, method = "ward.D2")
  plot(hc)
  clusters <- cutree(hc, k = k)
  clusters<-clusters |> as.data.frame() |> tibble::rownames_to_column(var="ID") |> dplyr::rename(Cluster=".")
  clusters$Cluster<-paste0("Cluster_",clusters$Cluster)
  return(clusters)
}

.genGT<-function(x,ClusterNum,P.adj=0.05,...){
  InnerDF<-x
  InnerDF<-InnerDF |> dplyr::left_join(enrichpws(InnerDF$ID,InnerDF$geneID,ClusterNum))
  InnerDF<-InnerDF |> dplyr::filter(pvalue<0.05,Count>=5,p.adjust<P.adj) |> dplyr::select(-c(pvalue,qvalue,BgRatio)) # Need Fix
  obj<-InnerDF |>
    dplyr::mutate(PCT=sapply(InnerDF$GeneRatio,function(x)eval(parse(text = x)))*100) |>
    dplyr::mutate(Padj = signif(p.adjust, 2)) |>
    dplyr::select(Description,ID,Count,Cluster,PCT,Padj,geneID) |>
    dplyr::mutate(geneID=gsub("/"," ,",geneID))|>
    gt::gt(groupname_col = "Cluster") |>
    gtExtras::gt_plt_bar_pct(column = PCT, scaled = FALSE, fill = "blue", background = "lightblue") |>
    gtExtras::gt_hulk_col_numeric(Padj) |>
    gtExtras::gt_plt_bar(column = Count, scaled = TRUE,color = "#e64047")  |>
    gtExtras::gt_merge_stack(col2 = ID, col1 = Description) |>
    gt::cols_width(Count ~ px(100),
               PCT ~ px(200)) |>
    gt::tab_style(
      style = cell_text(size = px(13)),
      locations = cells_body()
    ) |>
    gt::tab_header(title = "Enrichment Result",subtitle = paste0("Split into ",k, " Clusters. Generated by zhimingye/Enrich2GT"))
  return(obj)
}
