# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ora_analysis <- function(gene_sets, input_genes, background_genes) {
    .Call('_EnrichGT_ora_analysis', PACKAGE = 'EnrichGT', gene_sets, input_genes, background_genes)
}

