# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gseaScores2 <- function(stats, hitIndices, exponent = 1.0) {
    .Call('_EnrichGT_gseaScores2', PACKAGE = 'EnrichGT', stats, hitIndices, exponent)
}

ora_analysis <- function(gene_sets, input_genes, background_genes) {
    .Call('_EnrichGT_ora_analysis', PACKAGE = 'EnrichGT', gene_sets, input_genes, background_genes)
}

