name: Deploy to gh_pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出 main 分支的代码
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false  # 防止覆盖令牌
          submodules: true  # 如果有子模块需要检出

      # 步骤 2: 清除不需要的 Git 配置
      - name: Clean Git configurations
        run: |
          # 清除 core.sshCommand
          git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || true

          # 清除 http.https://github.com/.extraheader
          git config --local --name-only --get-regexp 'http\.https://github\.com/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || true

          # 对所有子模块执行相同操作
          git submodule foreach --recursive 'git config --local --name-only --get-regexp "core\.sshCommand" && git config --local --unset-all "core.sshCommand" || true'
          git submodule foreach --recursive 'git config --local --name-only --get-regexp "http\.https://github\.com/\.extraheader" && git config --local --unset-all "http.https://github.com/.extraheader" || true'

      # 步骤 3: 设置 Git 用户信息
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 步骤 4: 复制 site/_site 内容到临时目录
      - name: Archive site/_site
        run: |
          mkdir -p ../_site_temp
          cp -r site/_site/* ../_site_temp/

      # 步骤 5: 检出 gh_pages 分支
      - name: Checkout gh_pages branch
        uses: actions/checkout@v3
        with:
          ref: gh_pages
          persist-credentials: false

      # 步骤 6: 复制文件到 gh_pages 分支
      - name: Copy files to gh_pages
        run: |
          rm -rf *  # 请根据需要谨慎使用，避免误删重要文件
          cp -r ../_site_temp/* ./

      # 步骤 7: 提交并推送更改
      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Update gh_pages with latest site/_site from main" || echo "No changes to commit"
          git push origin gh_pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
